In [2]:
import pandas as pd

In [4]:
base_dados_df = pd.read_excel(r'Arquivos/Vendas_Jan.xlsx')

#Imprimir os dados
display(base_dados_df)

            Vendedor                        Produto Data Venda  Total Vendas
0   Leonardo Almeida                 Tênis Feminino 2023-01-01        719.92
1     Eliane Moreira          Calça Feminina Jogger 2023-01-02        139.98
2    Nicolas Pereira               Camisa Masculina 2023-01-03        306.80
3     Amanda Martins              Bermuda Masculino 2023-01-04       1485.60
4       Paulo Santos  Camisa Masculina Festa Balada 2023-01-05        876.84
5    Gabriel Cardoso                 Bota Masculina 2023-01-06        448.28
6   Leonardo Almeida        Jaqueta Masculina Preta 2023-01-07        602.00
7     Eliane Moreira              Bolsa de Trabalho 2023-01-08        994.92
8    Nicolas Pereira    Kit de Pinceis de Maquiagem 2023-01-09       1048.68
9     Amanda Martins               Vestido Infantil 2023-01-10         59.90
10  Leonardo Almeida                Calça Bailarina 2023-01-11        281.40
11    Eliane Moreira                 Camisa Térmica 2023-01-12         83.80
12   Nicolas Pereira                  Sapato Social 2023-01-13        573.30
13    Amanda Martins               Sapatilha Sapato 2023-01-14        503.10
14    Eliane Moreira                 Colar Pingente 2023-01-15        719.20
15      Angela Maria                 Tênis Feminino 2023-01-16        359.96
16    Carlos Moreira          Calça Feminina Jogger 2023-01-17        489.93
17    Eliane Moreira               Camisa Masculina 2023-01-18       1073.80
18   Nicolas Pereira              Bermuda Masculino 2023-01-19       1039.92
19  Leonardo Almeida  Camisa Masculina Festa Balada 2023-01-20       1315.26
20   Gabriel Cardoso                 Bota Masculina 2023-01-21       1344.84
21  Leonardo Almeida        Jaqueta Masculina Preta 2023-01-22        903.00
22    Eliane Moreira              Bolsa de Trabalho 2023-01-23        994.92
23   Nicolas Pereira    Kit de Pinceis de Maquiagem 2023-01-24       1048.68
24    Amanda Martins               Vestido Infantil 2023-01-25        479.20
25    Eliane Moreira                Calça Bailarina 2023-01-26        234.50
26   Nicolas Pereira                 Camisa Térmica 2023-01-27        377.10
27    Amanda Martins                  Sapato Social 2023-01-28        737.10

In [ ]:
#subset = Coluna que queremos remover
#keep = Instrução do qual valor vai permanecer
removendo_duplicidades = base_dados_df.drop_duplicates(subset="Vendedor", keep="first")

display(removendo_duplicidades)

            Vendedor                        Produto Data Venda  Total Vendas
0   Leonardo Almeida                 Tênis Feminino 2023-01-01        719.92
1     Eliane Moreira          Calça Feminina Jogger 2023-01-02        139.98
2    Nicolas Pereira               Camisa Masculina 2023-01-03        306.80
3     Amanda Martins              Bermuda Masculino 2023-01-04       1485.60
4       Paulo Santos  Camisa Masculina Festa Balada 2023-01-05        876.84
5    Gabriel Cardoso                 Bota Masculina 2023-01-06        448.28
15      Angela Maria                 Tênis Feminino 2023-01-16        359.96
16    Carlos Moreira          Calça Feminina Jogger 2023-01-17        489.93

In [ ]:
# Salvando os arquivos em csv
for vendedor in removendo_duplicidades['Vendedor']:
    vendas_funcionarios = base_dados_df.loc[base_dados_df['Vendedor'] == vendedor]
    vendas_funcionarios.to_csv(f'Arquivos\Automação\Relatorio vendas {vendedor}.csv', index=False)

In [ ]:
# Salvando os arquivos em excel
for vendedor in removendo_duplicidades['Vendedor']:
    vendas_funcionarios = base_dados_df.loc[base_dados_df['Vendedor'] == vendedor]
    vendas_funcionarios.to_excel(f'Arquivos\Automação\Relatorio vendas {vendedor}.xlsx', index=False)